// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWzkKu1jh2s0ynglMyKhx9AnMD2bg3LQ',
    appId: '1:808844841687:web:a2ab208435446e6a7fd692',
    messagingSenderId: '808844841687',
    projectId: 'authtutorial-3ebab',
    authDomain: 'authtutorial-3ebab.firebaseapp.com',
    storageBucket: 'authtutorial-3ebab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ6WpjYhSNSU7qQGlqv6W6pTZD5skNWhA',
    appId: '1:808844841687:android:22dd216b2bb11fcf7fd692',
    messagingSenderId: '808844841687',
    projectId: 'authtutorial-3ebab',
    storageBucket: 'authtutorial-3ebab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMrE5DkcmdN3SheQqhl2gHEiFpg9ba5Q',
    appId: '1:808844841687:ios:e66efb4abaeaf3217fd692',
    messagingSenderId: '808844841687',
    projectId: 'authtutorial-3ebab',
    storageBucket: 'authtutorial-3ebab.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterWidth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxMrE5DkcmdN3SheQqhl2gHEiFpg9ba5Q',
    appId: '1:808844841687:ios:e66efb4abaeaf3217fd692',
    messagingSenderId: '808844841687',
    projectId: 'authtutorial-3ebab',
    storageBucket: 'authtutorial-3ebab.appspot.com',
    iosBundleId: 'com.example.firebaseFlutterWidth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwWzkKu1jh2s0ynglMyKhx9AnMD2bg3LQ',
    appId: '1:808844841687:web:fd184ac9f05c0f6c7fd692',
    messagingSenderId: '808844841687',
    projectId: 'authtutorial-3ebab',
    authDomain: 'authtutorial-3ebab.firebaseapp.com',
    storageBucket: 'authtutorial-3ebab.appspot.com',
  );
}
